apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: "https://github.com/YacqubAdan/eks-gitops-ci-cd.git"
    targetRevision: HEAD
    path: argocd/apps

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true